 steps: 
  - name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'gs://test3-308406_bucket/results.zip', 'previous_results.zip']
  # operations that use previous_results.zip and produce new_results.zip
  - name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'new_results.zip', 'gs://test3-308406_bucket/results.zip']
 # Build the container image
 - name: 'gcr.io/cloud-builders/mvn'
   args: ['clean', 'package', 'jib:build', '-Dimage=gcr.io/$PROJECT_ID/res-test:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'res-test'
   - '--image'
   - 'gcr.io/$PROJECT_ID/res-test:$COMMIT_SHA'
   - '--region'
   - 'us-central1'
   - '--memory'
   - '512M'
   - '--platform'
   - 'managed'